!generation.Seq2Seq
src_embedding: !generation.Sequential
  embedding: !torch.Embedding
    num_embeddings: 12071
    embedding_dim: 256
  positional: !generation.PositionalEncoding
    d_model: 256
    max_len: 5000
tgt_embedding: !generation.Sequential
  embedding: !torch.Embedding
    num_embeddings: 8836
    embedding_dim: 256
  positional: !generation.PositionalEncoding
    d_model: 256
    max_len: 5000
embedding_dropout: 0.1
encoder: !generation.TransformerEncoder
  input_size: 256
  d_model: 256
  nhead: 4
  num_layers: 8
  dim_feedforward: 1024
  dropout: 0.1
decoder: !generation.TransformerDecoder
  input_size: 256
  d_model: 256
  nhead: 4
  num_layers: 8
  dim_feedforward: 1024
  dropout: 0.1
output_layer: !torch.Linear
  in_features: 256
  out_features: 8836
dropout: 0.1
weight_tying:
  output_layer: tgt_embedding.embedding
src_padding_idx: 0
tgt_padding_idx: 0
